### ISSUE TITLE
Improve lint in the project

### ISSUE THREAD

**Issue by afucher** [InnerSourceCommons/awesome-innersource#15]
- [x] Make the github check for lint runs without need of an approval. It will give feedback early to the contributor. For example in this [PR](https://github.com/InnerSourceCommons/awesome-innersource/pull/14) it has a lot of time without approval, that can be used to fix lint issues.
- [ ] Add instructions to run the lint locally in the CONTRIBUTING.md

**Comment by spier** [comment]
I changed the settings related to GHA workflows to the following
> Require approval for first-time contributors who are new to GitHub

This will make the workflow, awesome-lint in this case, run automatically for more contributors automatically.

**Comment by spier** [comment]
I don't really know awesome-lint that well. Also as I don't see a config file anywhere, I am assuming we are using it in its default configuration?

Lastly I did see a lot of these annotations in the markdown files, and was wondering if there is a way to get rid of them?
`<!--lint ignore double-link-->`

@afucher if you have a proposal for the type of instructions you are looking for as a contributor, please let us know. Or if you have time, we are always happy to accept your contribution :)

**Comment by afucher** [comment]
>Lastly I did see a lot of these annotations in the markdown files, and was wondering if there is a way to get rid of them?  

Good question, is the first time that I saw this linter. I'll try to take a look if there is an easy way to configure the rules instead of adding those `ignore` to the file.


>@afucher if you have a proposal for the type of instructions you are looking for as a contributor, please let us know. Or if you have time, we are always happy to accept your contribution :)  

Yes, I have an idea. Next week I can send a PR with a proposal.
