### ISSUE TITLE
Link to FINOS InnerSource Special Interest Group (SIG)?

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/awesome-innersource#5]
I just found [resources.md](https://github.com/finos/InnerSource/blob/master/docs/resources.md) by the FINOS InnerSource Special Interest Group (SIG).

Looks like they also started collecting awesome resources about InnerSource.
However they came roughly as far as we are in this repo so far :)

Mostly they are linking to resources from the ISC anyways.

So maybe the only thing for us to do for the moment would be to link to the [repo](https://github.com/finos/InnerSource) to say "there is such a think as the FINOS InnerSource SIG"?

@claredillon or @clcoffey does the FINOS InnerSource SIG already have a website where they publish InnerSource-related content? Or is it just this repo for now?

**Comment by clcoffey** [comment]
There is this website for the InnerSource Sig https://innersource.finos.org/

At the bottom of the page you will find a link to resources and a link to the maturity matrix

**Comment by pmalirz** [comment]
Thanks for sharing @spier. We can link FINOS InnerSource SIG in our awesome repo as a community gathered specifically around the FINOS. I'm probably biased but I think we should keep on developing ours and even inform them and invite them to the contribution.

**Comment by spier** [comment]
Agreed, and PR sent :)

**Comment by rrrutledge** [comment]
> a link to the maturity matrix

It just links back to the same page.

**Comment by rrrutledge** [comment]
After you get our `awesome` repo in a state where it provides a notable amount of value, send a PR to the FINOS [resources.md](https://github.com/finos/InnerSource/blob/master/docs/resources.md) to link back to our `awesome` repo.  Then they can decide to merge the PR or if they just want to link straight to us from their landing pages.

**Comment by clcoffey** [comment]
> It just links back to the same page.

For me the Maturity Matrix links to https://innersource.finos.org/docs/maturity-matrix/intro

**Comment by rrrutledge** [comment]
I see, there is more than one link on the page to the maturity matrix.  The green ones work for me, but the red one does not.

![image](https://user-images.githubusercontent.com/9609562/204342506-2e8e6d99-91f9-4f93-bba0-5449a6d8fe47.png)

I opened a [pull request](https://github.com/finos/InnerSource/pull/79) to fix the broken link.

**Comment by spier** [comment]
Yeah, they have various broken links on their page unfortunately.
I also sent them a PR to fix one of them already.

Maybe I should sent a PR for a link checker instead :)
